// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoMS.Server.Data;

#nullable disable

namespace MoMS.Server.Migrations
{
    [DbContext(typeof(MoMsDbContext))]
    partial class MoMsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoMS.Server.Models.Entities.ListDocket", b =>
                {
                    b.Property<string>("PdfName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("PDF_NAME");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATETIME");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ITEM");

                    b.Property<string>("SNum")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("S_NUM");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VENDOR");

                    b.Property<int?>("YearCreated")
                        .HasColumnType("int")
                        .HasColumnName("YEAR_CREATED");

                    b.HasKey("PdfName");

                    b.ToTable("list_docket");
                });

            modelBuilder.Entity("MoMS.Server.Models.Entities.ListOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("category");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Value")
                        .IsUnique();

                    b.ToTable("list_option");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "mould_maker",
                            SortOrder = 1,
                            Value = "RB"
                        },
                        new
                        {
                            Id = 2,
                            Category = "mould_maker",
                            SortOrder = 2,
                            Value = "V. TOPLAS"
                        },
                        new
                        {
                            Id = 3,
                            Category = "mould_maker",
                            SortOrder = 3,
                            Value = "YH. ENG"
                        },
                        new
                        {
                            Id = 4,
                            Category = "mould_maker",
                            SortOrder = 4,
                            Value = "GS MOULD"
                        },
                        new
                        {
                            Id = 5,
                            Category = "prepared",
                            SortOrder = 1,
                            Value = "Hew CP"
                        },
                        new
                        {
                            Id = 6,
                            Category = "prepared",
                            SortOrder = 2,
                            Value = "Low PS"
                        },
                        new
                        {
                            Id = 7,
                            Category = "prepared",
                            SortOrder = 3,
                            Value = "Ameera"
                        },
                        new
                        {
                            Id = 8,
                            Category = "prepared",
                            SortOrder = 4,
                            Value = "Kamarul"
                        },
                        new
                        {
                            Id = 9,
                            Category = "prepared",
                            SortOrder = 5,
                            Value = "Alif"
                        },
                        new
                        {
                            Id = 10,
                            Category = "production",
                            SortOrder = 1,
                            Value = "A5"
                        },
                        new
                        {
                            Id = 11,
                            Category = "production",
                            SortOrder = 2,
                            Value = "A6"
                        },
                        new
                        {
                            Id = 12,
                            Category = "production",
                            SortOrder = 3,
                            Value = "A7"
                        },
                        new
                        {
                            Id = 13,
                            Category = "production",
                            SortOrder = 4,
                            Value = "A8"
                        },
                        new
                        {
                            Id = 14,
                            Category = "production",
                            SortOrder = 5,
                            Value = "A9"
                        },
                        new
                        {
                            Id = 15,
                            Category = "production",
                            SortOrder = 6,
                            Value = "A10"
                        },
                        new
                        {
                            Id = 16,
                            Category = "production",
                            SortOrder = 7,
                            Value = "A12"
                        },
                        new
                        {
                            Id = 17,
                            Category = "production",
                            SortOrder = 8,
                            Value = "A13"
                        },
                        new
                        {
                            Id = 18,
                            Category = "production",
                            SortOrder = 9,
                            Value = "A14"
                        },
                        new
                        {
                            Id = 19,
                            Category = "production",
                            SortOrder = 10,
                            Value = "A15"
                        },
                        new
                        {
                            Id = 20,
                            Category = "production",
                            SortOrder = 11,
                            Value = "A16"
                        },
                        new
                        {
                            Id = 21,
                            Category = "production",
                            SortOrder = 12,
                            Value = "A17"
                        },
                        new
                        {
                            Id = 22,
                            Category = "production",
                            SortOrder = 13,
                            Value = "A18"
                        },
                        new
                        {
                            Id = 23,
                            Category = "production",
                            SortOrder = 14,
                            Value = "A19"
                        },
                        new
                        {
                            Id = 24,
                            Category = "production",
                            SortOrder = 15,
                            Value = "A21"
                        },
                        new
                        {
                            Id = 25,
                            Category = "purpose",
                            SortOrder = 1,
                            Value = "Sample/Development"
                        },
                        new
                        {
                            Id = 26,
                            Category = "purpose",
                            SortOrder = 2,
                            Value = "Repair"
                        },
                        new
                        {
                            Id = 27,
                            Category = "purpose",
                            SortOrder = 3,
                            Value = "Modification"
                        },
                        new
                        {
                            Id = 28,
                            Category = "purpose",
                            SortOrder = 4,
                            Value = "Service"
                        },
                        new
                        {
                            Id = 29,
                            Category = "vendor",
                            SortOrder = 1,
                            Value = "JLG"
                        },
                        new
                        {
                            Id = 30,
                            Category = "vendor",
                            SortOrder = 2,
                            Value = "SNS"
                        },
                        new
                        {
                            Id = 31,
                            Category = "vendor",
                            SortOrder = 3,
                            Value = "JUSEN"
                        },
                        new
                        {
                            Id = 32,
                            Category = "vendor",
                            SortOrder = 4,
                            Value = "MAGNUM"
                        },
                        new
                        {
                            Id = 33,
                            Category = "vendor",
                            SortOrder = 5,
                            Value = "SERVICE"
                        },
                        new
                        {
                            Id = 34,
                            Category = "rack",
                            SortOrder = 1,
                            Value = "1A"
                        },
                        new
                        {
                            Id = 35,
                            Category = "rack",
                            SortOrder = 2,
                            Value = "1B"
                        },
                        new
                        {
                            Id = 36,
                            Category = "rack",
                            SortOrder = 3,
                            Value = "1C"
                        },
                        new
                        {
                            Id = 37,
                            Category = "rack",
                            SortOrder = 4,
                            Value = "1D"
                        },
                        new
                        {
                            Id = 38,
                            Category = "rack",
                            SortOrder = 5,
                            Value = "2A"
                        },
                        new
                        {
                            Id = 39,
                            Category = "rack",
                            SortOrder = 6,
                            Value = "2B"
                        },
                        new
                        {
                            Id = 40,
                            Category = "rack",
                            SortOrder = 7,
                            Value = "2C"
                        },
                        new
                        {
                            Id = 41,
                            Category = "rack",
                            SortOrder = 8,
                            Value = "2D"
                        },
                        new
                        {
                            Id = 42,
                            Category = "rack",
                            SortOrder = 9,
                            Value = "3A"
                        },
                        new
                        {
                            Id = 43,
                            Category = "rack",
                            SortOrder = 10,
                            Value = "3B"
                        },
                        new
                        {
                            Id = 44,
                            Category = "rack",
                            SortOrder = 11,
                            Value = "3C"
                        },
                        new
                        {
                            Id = 45,
                            Category = "rack",
                            SortOrder = 12,
                            Value = "3D"
                        },
                        new
                        {
                            Id = 46,
                            Category = "rack",
                            SortOrder = 13,
                            Value = "4A"
                        },
                        new
                        {
                            Id = 47,
                            Category = "rack",
                            SortOrder = 14,
                            Value = "4B"
                        },
                        new
                        {
                            Id = 48,
                            Category = "rack",
                            SortOrder = 15,
                            Value = "4C"
                        },
                        new
                        {
                            Id = 49,
                            Category = "rack",
                            SortOrder = 16,
                            Value = "4D"
                        },
                        new
                        {
                            Id = 50,
                            Category = "rack",
                            SortOrder = 17,
                            Value = "5A"
                        },
                        new
                        {
                            Id = 51,
                            Category = "rack",
                            SortOrder = 18,
                            Value = "5B"
                        },
                        new
                        {
                            Id = 52,
                            Category = "rack",
                            SortOrder = 19,
                            Value = "5C"
                        },
                        new
                        {
                            Id = 53,
                            Category = "rack",
                            SortOrder = 20,
                            Value = "5D"
                        },
                        new
                        {
                            Id = 54,
                            Category = "rack",
                            SortOrder = 21,
                            Value = "6A"
                        },
                        new
                        {
                            Id = 55,
                            Category = "rack",
                            SortOrder = 22,
                            Value = "6B"
                        },
                        new
                        {
                            Id = 56,
                            Category = "rack",
                            SortOrder = 23,
                            Value = "6C"
                        },
                        new
                        {
                            Id = 57,
                            Category = "rack",
                            SortOrder = 24,
                            Value = "6D"
                        },
                        new
                        {
                            Id = 58,
                            Category = "rack",
                            SortOrder = 25,
                            Value = "7A"
                        },
                        new
                        {
                            Id = 59,
                            Category = "rack",
                            SortOrder = 26,
                            Value = "7B"
                        },
                        new
                        {
                            Id = 60,
                            Category = "rack",
                            SortOrder = 27,
                            Value = "7C"
                        },
                        new
                        {
                            Id = 61,
                            Category = "rack",
                            SortOrder = 28,
                            Value = "7D"
                        },
                        new
                        {
                            Id = 62,
                            Category = "rack",
                            SortOrder = 29,
                            Value = "8A"
                        },
                        new
                        {
                            Id = 63,
                            Category = "rack",
                            SortOrder = 30,
                            Value = "8B"
                        },
                        new
                        {
                            Id = 64,
                            Category = "rack",
                            SortOrder = 31,
                            Value = "8C"
                        },
                        new
                        {
                            Id = 65,
                            Category = "rack",
                            SortOrder = 32,
                            Value = "8D"
                        },
                        new
                        {
                            Id = 66,
                            Category = "rack",
                            SortOrder = 33,
                            Value = "9A"
                        },
                        new
                        {
                            Id = 67,
                            Category = "rack",
                            SortOrder = 34,
                            Value = "9B"
                        },
                        new
                        {
                            Id = 68,
                            Category = "rack",
                            SortOrder = 35,
                            Value = "9C"
                        },
                        new
                        {
                            Id = 69,
                            Category = "rack",
                            SortOrder = 36,
                            Value = "9D"
                        },
                        new
                        {
                            Id = 70,
                            Category = "rack",
                            SortOrder = 37,
                            Value = "10A"
                        },
                        new
                        {
                            Id = 71,
                            Category = "rack",
                            SortOrder = 38,
                            Value = "10B"
                        },
                        new
                        {
                            Id = 72,
                            Category = "rack",
                            SortOrder = 39,
                            Value = "10C"
                        },
                        new
                        {
                            Id = 73,
                            Category = "rack",
                            SortOrder = 40,
                            Value = "10D"
                        },
                        new
                        {
                            Id = 74,
                            Category = "rack",
                            SortOrder = 41,
                            Value = "11A"
                        },
                        new
                        {
                            Id = 75,
                            Category = "rack",
                            SortOrder = 42,
                            Value = "11B"
                        },
                        new
                        {
                            Id = 76,
                            Category = "rack",
                            SortOrder = 43,
                            Value = "11C"
                        },
                        new
                        {
                            Id = 77,
                            Category = "rack",
                            SortOrder = 44,
                            Value = "11D"
                        },
                        new
                        {
                            Id = 78,
                            Category = "rack",
                            SortOrder = 45,
                            Value = "12A"
                        },
                        new
                        {
                            Id = 79,
                            Category = "rack",
                            SortOrder = 46,
                            Value = "12B"
                        },
                        new
                        {
                            Id = 80,
                            Category = "rack",
                            SortOrder = 47,
                            Value = "12C"
                        },
                        new
                        {
                            Id = 81,
                            Category = "rack",
                            SortOrder = 48,
                            Value = "12D"
                        },
                        new
                        {
                            Id = 82,
                            Category = "rack",
                            SortOrder = 49,
                            Value = "13A"
                        },
                        new
                        {
                            Id = 83,
                            Category = "rack",
                            SortOrder = 50,
                            Value = "13B"
                        },
                        new
                        {
                            Id = 84,
                            Category = "rack",
                            SortOrder = 51,
                            Value = "13C"
                        },
                        new
                        {
                            Id = 85,
                            Category = "rack",
                            SortOrder = 52,
                            Value = "13D"
                        },
                        new
                        {
                            Id = 86,
                            Category = "rack",
                            SortOrder = 53,
                            Value = "14A"
                        },
                        new
                        {
                            Id = 87,
                            Category = "rack",
                            SortOrder = 54,
                            Value = "14B"
                        },
                        new
                        {
                            Id = 88,
                            Category = "rack",
                            SortOrder = 55,
                            Value = "14C"
                        },
                        new
                        {
                            Id = 89,
                            Category = "rack",
                            SortOrder = 56,
                            Value = "14D"
                        },
                        new
                        {
                            Id = 90,
                            Category = "rack",
                            SortOrder = 57,
                            Value = "15A"
                        },
                        new
                        {
                            Id = 91,
                            Category = "rack",
                            SortOrder = 58,
                            Value = "15B"
                        },
                        new
                        {
                            Id = 92,
                            Category = "rack",
                            SortOrder = 59,
                            Value = "15C"
                        },
                        new
                        {
                            Id = 93,
                            Category = "rack",
                            SortOrder = 60,
                            Value = "15D"
                        },
                        new
                        {
                            Id = 94,
                            Category = "rack",
                            SortOrder = 61,
                            Value = "16A"
                        },
                        new
                        {
                            Id = 95,
                            Category = "rack",
                            SortOrder = 62,
                            Value = "16B"
                        },
                        new
                        {
                            Id = 96,
                            Category = "rack",
                            SortOrder = 63,
                            Value = "16C"
                        },
                        new
                        {
                            Id = 97,
                            Category = "rack",
                            SortOrder = 64,
                            Value = "16D"
                        },
                        new
                        {
                            Id = 98,
                            Category = "rack",
                            SortOrder = 65,
                            Value = "17A"
                        },
                        new
                        {
                            Id = 99,
                            Category = "rack",
                            SortOrder = 66,
                            Value = "17B"
                        },
                        new
                        {
                            Id = 100,
                            Category = "rack",
                            SortOrder = 67,
                            Value = "17C"
                        },
                        new
                        {
                            Id = 101,
                            Category = "rack",
                            SortOrder = 68,
                            Value = "17D"
                        },
                        new
                        {
                            Id = 102,
                            Category = "rack",
                            SortOrder = 69,
                            Value = "18A"
                        },
                        new
                        {
                            Id = 103,
                            Category = "rack",
                            SortOrder = 70,
                            Value = "18B"
                        },
                        new
                        {
                            Id = 104,
                            Category = "rack",
                            SortOrder = 71,
                            Value = "18C"
                        },
                        new
                        {
                            Id = 105,
                            Category = "rack",
                            SortOrder = 72,
                            Value = "18D"
                        },
                        new
                        {
                            Id = 106,
                            Category = "rack",
                            SortOrder = 73,
                            Value = "19A"
                        },
                        new
                        {
                            Id = 107,
                            Category = "rack",
                            SortOrder = 74,
                            Value = "19B"
                        },
                        new
                        {
                            Id = 108,
                            Category = "rack",
                            SortOrder = 75,
                            Value = "19C"
                        },
                        new
                        {
                            Id = 109,
                            Category = "rack",
                            SortOrder = 76,
                            Value = "19D"
                        },
                        new
                        {
                            Id = 110,
                            Category = "rack",
                            SortOrder = 77,
                            Value = "20A"
                        },
                        new
                        {
                            Id = 111,
                            Category = "rack",
                            SortOrder = 78,
                            Value = "20B"
                        },
                        new
                        {
                            Id = 112,
                            Category = "rack",
                            SortOrder = 79,
                            Value = "20C"
                        },
                        new
                        {
                            Id = 113,
                            Category = "rack",
                            SortOrder = 80,
                            Value = "20D"
                        },
                        new
                        {
                            Id = 114,
                            Category = "rack",
                            SortOrder = 81,
                            Value = "21A"
                        },
                        new
                        {
                            Id = 115,
                            Category = "rack",
                            SortOrder = 82,
                            Value = "21B"
                        },
                        new
                        {
                            Id = 116,
                            Category = "rack",
                            SortOrder = 83,
                            Value = "21C"
                        },
                        new
                        {
                            Id = 117,
                            Category = "rack",
                            SortOrder = 84,
                            Value = "21D"
                        },
                        new
                        {
                            Id = 118,
                            Category = "rack",
                            SortOrder = 85,
                            Value = "22A"
                        },
                        new
                        {
                            Id = 119,
                            Category = "rack",
                            SortOrder = 86,
                            Value = "22B"
                        },
                        new
                        {
                            Id = 120,
                            Category = "rack",
                            SortOrder = 87,
                            Value = "22C"
                        },
                        new
                        {
                            Id = 121,
                            Category = "rack",
                            SortOrder = 88,
                            Value = "22D"
                        },
                        new
                        {
                            Id = 122,
                            Category = "rack",
                            SortOrder = 89,
                            Value = "23A"
                        },
                        new
                        {
                            Id = 123,
                            Category = "rack",
                            SortOrder = 90,
                            Value = "23B"
                        },
                        new
                        {
                            Id = 124,
                            Category = "rack",
                            SortOrder = 91,
                            Value = "23C"
                        },
                        new
                        {
                            Id = 125,
                            Category = "rack",
                            SortOrder = 92,
                            Value = "23D"
                        },
                        new
                        {
                            Id = 126,
                            Category = "rack",
                            SortOrder = 93,
                            Value = "24A"
                        },
                        new
                        {
                            Id = 127,
                            Category = "rack",
                            SortOrder = 94,
                            Value = "24B"
                        },
                        new
                        {
                            Id = 128,
                            Category = "rack",
                            SortOrder = 95,
                            Value = "24C"
                        },
                        new
                        {
                            Id = 129,
                            Category = "rack",
                            SortOrder = 96,
                            Value = "24D"
                        },
                        new
                        {
                            Id = 130,
                            Category = "rack",
                            SortOrder = 97,
                            Value = "25A"
                        },
                        new
                        {
                            Id = 131,
                            Category = "rack",
                            SortOrder = 98,
                            Value = "25B"
                        },
                        new
                        {
                            Id = 132,
                            Category = "rack",
                            SortOrder = 99,
                            Value = "25C"
                        },
                        new
                        {
                            Id = 133,
                            Category = "rack",
                            SortOrder = 100,
                            Value = "25D"
                        },
                        new
                        {
                            Id = 134,
                            Category = "rack",
                            SortOrder = 101,
                            Value = "26A"
                        },
                        new
                        {
                            Id = 135,
                            Category = "rack",
                            SortOrder = 102,
                            Value = "26B"
                        },
                        new
                        {
                            Id = 136,
                            Category = "rack",
                            SortOrder = 103,
                            Value = "26C"
                        },
                        new
                        {
                            Id = 137,
                            Category = "rack",
                            SortOrder = 104,
                            Value = "26D"
                        },
                        new
                        {
                            Id = 138,
                            Category = "rack",
                            SortOrder = 105,
                            Value = "A1"
                        },
                        new
                        {
                            Id = 139,
                            Category = "rack",
                            SortOrder = 106,
                            Value = "A2"
                        },
                        new
                        {
                            Id = 140,
                            Category = "rack",
                            SortOrder = 107,
                            Value = "A3"
                        },
                        new
                        {
                            Id = 141,
                            Category = "rack",
                            SortOrder = 108,
                            Value = "A4"
                        },
                        new
                        {
                            Id = 142,
                            Category = "rack",
                            SortOrder = 109,
                            Value = "A5"
                        },
                        new
                        {
                            Id = 143,
                            Category = "rack",
                            SortOrder = 110,
                            Value = "A6"
                        },
                        new
                        {
                            Id = 144,
                            Category = "rack",
                            SortOrder = 111,
                            Value = "A7"
                        },
                        new
                        {
                            Id = 145,
                            Category = "rack",
                            SortOrder = 112,
                            Value = "A8"
                        },
                        new
                        {
                            Id = 146,
                            Category = "rack",
                            SortOrder = 113,
                            Value = "A9"
                        },
                        new
                        {
                            Id = 147,
                            Category = "rack",
                            SortOrder = 114,
                            Value = "A10"
                        },
                        new
                        {
                            Id = 148,
                            Category = "rack",
                            SortOrder = 115,
                            Value = "A11"
                        },
                        new
                        {
                            Id = 149,
                            Category = "rack",
                            SortOrder = 116,
                            Value = "A12"
                        },
                        new
                        {
                            Id = 150,
                            Category = "rack",
                            SortOrder = 117,
                            Value = "A13"
                        },
                        new
                        {
                            Id = 151,
                            Category = "rack",
                            SortOrder = 118,
                            Value = "A14"
                        },
                        new
                        {
                            Id = 152,
                            Category = "rack",
                            SortOrder = 119,
                            Value = "A15"
                        },
                        new
                        {
                            Id = 153,
                            Category = "rack",
                            SortOrder = 120,
                            Value = "A16"
                        },
                        new
                        {
                            Id = 154,
                            Category = "rack",
                            SortOrder = 121,
                            Value = "A17"
                        },
                        new
                        {
                            Id = 155,
                            Category = "rack",
                            SortOrder = 122,
                            Value = "A18"
                        },
                        new
                        {
                            Id = 156,
                            Category = "rack",
                            SortOrder = 123,
                            Value = "A19"
                        },
                        new
                        {
                            Id = 157,
                            Category = "rack",
                            SortOrder = 124,
                            Value = "A20"
                        },
                        new
                        {
                            Id = 158,
                            Category = "rack",
                            SortOrder = 125,
                            Value = "A21"
                        },
                        new
                        {
                            Id = 159,
                            Category = "rack",
                            SortOrder = 126,
                            Value = "A22"
                        },
                        new
                        {
                            Id = 160,
                            Category = "rack",
                            SortOrder = 127,
                            Value = "A23"
                        },
                        new
                        {
                            Id = 161,
                            Category = "rack",
                            SortOrder = 128,
                            Value = "A24"
                        },
                        new
                        {
                            Id = 162,
                            Category = "rack",
                            SortOrder = 129,
                            Value = "B1"
                        },
                        new
                        {
                            Id = 163,
                            Category = "rack",
                            SortOrder = 130,
                            Value = "B2"
                        },
                        new
                        {
                            Id = 164,
                            Category = "rack",
                            SortOrder = 131,
                            Value = "B3"
                        },
                        new
                        {
                            Id = 165,
                            Category = "rack",
                            SortOrder = 132,
                            Value = "B4"
                        },
                        new
                        {
                            Id = 166,
                            Category = "rack",
                            SortOrder = 133,
                            Value = "B5"
                        },
                        new
                        {
                            Id = 167,
                            Category = "rack",
                            SortOrder = 134,
                            Value = "B6"
                        },
                        new
                        {
                            Id = 168,
                            Category = "rack",
                            SortOrder = 135,
                            Value = "B7"
                        },
                        new
                        {
                            Id = 169,
                            Category = "rack",
                            SortOrder = 136,
                            Value = "B8"
                        },
                        new
                        {
                            Id = 170,
                            Category = "rack",
                            SortOrder = 137,
                            Value = "B9"
                        },
                        new
                        {
                            Id = 171,
                            Category = "rack",
                            SortOrder = 138,
                            Value = "B10"
                        },
                        new
                        {
                            Id = 172,
                            Category = "rack",
                            SortOrder = 139,
                            Value = "B11"
                        },
                        new
                        {
                            Id = 173,
                            Category = "rack",
                            SortOrder = 140,
                            Value = "B12"
                        },
                        new
                        {
                            Id = 174,
                            Category = "rack",
                            SortOrder = 141,
                            Value = "B13"
                        },
                        new
                        {
                            Id = 175,
                            Category = "rack",
                            SortOrder = 142,
                            Value = "B14"
                        },
                        new
                        {
                            Id = 176,
                            Category = "rack",
                            SortOrder = 143,
                            Value = "B15"
                        },
                        new
                        {
                            Id = 177,
                            Category = "rack",
                            SortOrder = 144,
                            Value = "B16"
                        },
                        new
                        {
                            Id = 178,
                            Category = "rack",
                            SortOrder = 145,
                            Value = "B17"
                        },
                        new
                        {
                            Id = 179,
                            Category = "rack",
                            SortOrder = 146,
                            Value = "B18"
                        },
                        new
                        {
                            Id = 180,
                            Category = "rack",
                            SortOrder = 147,
                            Value = "B19"
                        },
                        new
                        {
                            Id = 181,
                            Category = "rack",
                            SortOrder = 148,
                            Value = "B20"
                        },
                        new
                        {
                            Id = 182,
                            Category = "rack",
                            SortOrder = 149,
                            Value = "B21"
                        },
                        new
                        {
                            Id = 183,
                            Category = "rack",
                            SortOrder = 150,
                            Value = "B22"
                        },
                        new
                        {
                            Id = 184,
                            Category = "rack",
                            SortOrder = 151,
                            Value = "B23"
                        },
                        new
                        {
                            Id = 185,
                            Category = "rack",
                            SortOrder = 152,
                            Value = "B24"
                        },
                        new
                        {
                            Id = 186,
                            Category = "rack",
                            SortOrder = 153,
                            Value = "C1"
                        },
                        new
                        {
                            Id = 187,
                            Category = "rack",
                            SortOrder = 154,
                            Value = "C2"
                        },
                        new
                        {
                            Id = 188,
                            Category = "rack",
                            SortOrder = 155,
                            Value = "C3"
                        },
                        new
                        {
                            Id = 189,
                            Category = "rack",
                            SortOrder = 156,
                            Value = "C4"
                        },
                        new
                        {
                            Id = 190,
                            Category = "rack",
                            SortOrder = 157,
                            Value = "C5"
                        },
                        new
                        {
                            Id = 191,
                            Category = "rack",
                            SortOrder = 158,
                            Value = "C6"
                        },
                        new
                        {
                            Id = 192,
                            Category = "rack",
                            SortOrder = 159,
                            Value = "C7"
                        },
                        new
                        {
                            Id = 193,
                            Category = "rack",
                            SortOrder = 160,
                            Value = "C8"
                        },
                        new
                        {
                            Id = 194,
                            Category = "rack",
                            SortOrder = 161,
                            Value = "C9"
                        },
                        new
                        {
                            Id = 195,
                            Category = "rack",
                            SortOrder = 162,
                            Value = "C10"
                        },
                        new
                        {
                            Id = 196,
                            Category = "rack",
                            SortOrder = 163,
                            Value = "C11"
                        },
                        new
                        {
                            Id = 197,
                            Category = "rack",
                            SortOrder = 164,
                            Value = "C12"
                        },
                        new
                        {
                            Id = 198,
                            Category = "rack",
                            SortOrder = 165,
                            Value = "C13"
                        },
                        new
                        {
                            Id = 199,
                            Category = "rack",
                            SortOrder = 166,
                            Value = "C14"
                        },
                        new
                        {
                            Id = 200,
                            Category = "rack",
                            SortOrder = 167,
                            Value = "C15"
                        },
                        new
                        {
                            Id = 201,
                            Category = "rack",
                            SortOrder = 168,
                            Value = "C16"
                        },
                        new
                        {
                            Id = 202,
                            Category = "rack",
                            SortOrder = 169,
                            Value = "C17"
                        },
                        new
                        {
                            Id = 203,
                            Category = "rack",
                            SortOrder = 170,
                            Value = "C18"
                        },
                        new
                        {
                            Id = 204,
                            Category = "rack",
                            SortOrder = 171,
                            Value = "C19"
                        },
                        new
                        {
                            Id = 205,
                            Category = "rack",
                            SortOrder = 172,
                            Value = "C20"
                        },
                        new
                        {
                            Id = 206,
                            Category = "rack",
                            SortOrder = 173,
                            Value = "C21"
                        },
                        new
                        {
                            Id = 207,
                            Category = "rack",
                            SortOrder = 174,
                            Value = "C22"
                        },
                        new
                        {
                            Id = 208,
                            Category = "rack",
                            SortOrder = 175,
                            Value = "C23"
                        },
                        new
                        {
                            Id = 209,
                            Category = "rack",
                            SortOrder = 176,
                            Value = "C24"
                        },
                        new
                        {
                            Id = 210,
                            Category = "rack",
                            SortOrder = 177,
                            Value = "D1"
                        },
                        new
                        {
                            Id = 211,
                            Category = "rack",
                            SortOrder = 178,
                            Value = "D2"
                        },
                        new
                        {
                            Id = 212,
                            Category = "rack",
                            SortOrder = 179,
                            Value = "D3"
                        },
                        new
                        {
                            Id = 213,
                            Category = "rack",
                            SortOrder = 180,
                            Value = "D4"
                        },
                        new
                        {
                            Id = 214,
                            Category = "rack",
                            SortOrder = 181,
                            Value = "D5"
                        },
                        new
                        {
                            Id = 215,
                            Category = "rack",
                            SortOrder = 182,
                            Value = "D6"
                        },
                        new
                        {
                            Id = 216,
                            Category = "rack",
                            SortOrder = 183,
                            Value = "D7"
                        },
                        new
                        {
                            Id = 217,
                            Category = "rack",
                            SortOrder = 184,
                            Value = "D8"
                        },
                        new
                        {
                            Id = 218,
                            Category = "rack",
                            SortOrder = 185,
                            Value = "D9"
                        },
                        new
                        {
                            Id = 219,
                            Category = "rack",
                            SortOrder = 186,
                            Value = "D10"
                        },
                        new
                        {
                            Id = 220,
                            Category = "rack",
                            SortOrder = 187,
                            Value = "D11"
                        },
                        new
                        {
                            Id = 221,
                            Category = "rack",
                            SortOrder = 188,
                            Value = "D12"
                        },
                        new
                        {
                            Id = 222,
                            Category = "rack",
                            SortOrder = 189,
                            Value = "D13"
                        },
                        new
                        {
                            Id = 223,
                            Category = "rack",
                            SortOrder = 190,
                            Value = "D14"
                        },
                        new
                        {
                            Id = 224,
                            Category = "rack",
                            SortOrder = 191,
                            Value = "D15"
                        },
                        new
                        {
                            Id = 225,
                            Category = "rack",
                            SortOrder = 192,
                            Value = "D16"
                        },
                        new
                        {
                            Id = 226,
                            Category = "rack",
                            SortOrder = 193,
                            Value = "D17"
                        },
                        new
                        {
                            Id = 227,
                            Category = "rack",
                            SortOrder = 194,
                            Value = "D18"
                        },
                        new
                        {
                            Id = 228,
                            Category = "rack",
                            SortOrder = 195,
                            Value = "D19"
                        },
                        new
                        {
                            Id = 229,
                            Category = "rack",
                            SortOrder = 196,
                            Value = "D20"
                        },
                        new
                        {
                            Id = 230,
                            Category = "rack",
                            SortOrder = 197,
                            Value = "D21"
                        },
                        new
                        {
                            Id = 231,
                            Category = "rack",
                            SortOrder = 198,
                            Value = "D22"
                        },
                        new
                        {
                            Id = 232,
                            Category = "rack",
                            SortOrder = 199,
                            Value = "D23"
                        },
                        new
                        {
                            Id = 233,
                            Category = "rack",
                            SortOrder = 200,
                            Value = "D24"
                        },
                        new
                        {
                            Id = 234,
                            Category = "rack",
                            SortOrder = 201,
                            Value = "E1"
                        },
                        new
                        {
                            Id = 235,
                            Category = "rack",
                            SortOrder = 202,
                            Value = "E2"
                        },
                        new
                        {
                            Id = 236,
                            Category = "rack",
                            SortOrder = 203,
                            Value = "E3"
                        },
                        new
                        {
                            Id = 237,
                            Category = "rack",
                            SortOrder = 204,
                            Value = "E4"
                        },
                        new
                        {
                            Id = 238,
                            Category = "rack",
                            SortOrder = 205,
                            Value = "E5"
                        },
                        new
                        {
                            Id = 239,
                            Category = "rack",
                            SortOrder = 206,
                            Value = "E6"
                        },
                        new
                        {
                            Id = 240,
                            Category = "rack",
                            SortOrder = 207,
                            Value = "E7"
                        },
                        new
                        {
                            Id = 241,
                            Category = "rack",
                            SortOrder = 208,
                            Value = "E8"
                        },
                        new
                        {
                            Id = 242,
                            Category = "rack",
                            SortOrder = 209,
                            Value = "E9"
                        },
                        new
                        {
                            Id = 243,
                            Category = "rack",
                            SortOrder = 210,
                            Value = "E10"
                        },
                        new
                        {
                            Id = 244,
                            Category = "rack",
                            SortOrder = 211,
                            Value = "E11"
                        },
                        new
                        {
                            Id = 245,
                            Category = "rack",
                            SortOrder = 212,
                            Value = "E12"
                        },
                        new
                        {
                            Id = 246,
                            Category = "rack",
                            SortOrder = 213,
                            Value = "E13"
                        },
                        new
                        {
                            Id = 247,
                            Category = "rack",
                            SortOrder = 214,
                            Value = "E14"
                        },
                        new
                        {
                            Id = 248,
                            Category = "rack",
                            SortOrder = 215,
                            Value = "E15"
                        },
                        new
                        {
                            Id = 249,
                            Category = "rack",
                            SortOrder = 216,
                            Value = "E16"
                        },
                        new
                        {
                            Id = 250,
                            Category = "rack",
                            SortOrder = 217,
                            Value = "E17"
                        },
                        new
                        {
                            Id = 251,
                            Category = "rack",
                            SortOrder = 218,
                            Value = "E18"
                        },
                        new
                        {
                            Id = 252,
                            Category = "rack",
                            SortOrder = 219,
                            Value = "E19"
                        },
                        new
                        {
                            Id = 253,
                            Category = "rack",
                            SortOrder = 220,
                            Value = "E20"
                        },
                        new
                        {
                            Id = 254,
                            Category = "rack",
                            SortOrder = 221,
                            Value = "E21"
                        },
                        new
                        {
                            Id = 255,
                            Category = "rack",
                            SortOrder = 222,
                            Value = "E22"
                        },
                        new
                        {
                            Id = 256,
                            Category = "rack",
                            SortOrder = 223,
                            Value = "E23"
                        },
                        new
                        {
                            Id = 257,
                            Category = "rack",
                            SortOrder = 224,
                            Value = "E24"
                        },
                        new
                        {
                            Id = 258,
                            Category = "rack",
                            SortOrder = 225,
                            Value = "F1"
                        },
                        new
                        {
                            Id = 259,
                            Category = "rack",
                            SortOrder = 226,
                            Value = "F2"
                        },
                        new
                        {
                            Id = 260,
                            Category = "rack",
                            SortOrder = 227,
                            Value = "F3"
                        },
                        new
                        {
                            Id = 261,
                            Category = "rack",
                            SortOrder = 228,
                            Value = "F4"
                        },
                        new
                        {
                            Id = 262,
                            Category = "rack",
                            SortOrder = 229,
                            Value = "F5"
                        },
                        new
                        {
                            Id = 263,
                            Category = "rack",
                            SortOrder = 230,
                            Value = "F6"
                        },
                        new
                        {
                            Id = 264,
                            Category = "rack",
                            SortOrder = 231,
                            Value = "F7"
                        },
                        new
                        {
                            Id = 265,
                            Category = "rack",
                            SortOrder = 232,
                            Value = "F8"
                        },
                        new
                        {
                            Id = 266,
                            Category = "rack",
                            SortOrder = 233,
                            Value = "F9"
                        },
                        new
                        {
                            Id = 267,
                            Category = "rack",
                            SortOrder = 234,
                            Value = "F10"
                        },
                        new
                        {
                            Id = 268,
                            Category = "rack",
                            SortOrder = 235,
                            Value = "F11"
                        },
                        new
                        {
                            Id = 269,
                            Category = "rack",
                            SortOrder = 236,
                            Value = "F12"
                        },
                        new
                        {
                            Id = 270,
                            Category = "rack",
                            SortOrder = 237,
                            Value = "F13"
                        },
                        new
                        {
                            Id = 271,
                            Category = "rack",
                            SortOrder = 238,
                            Value = "F14"
                        },
                        new
                        {
                            Id = 272,
                            Category = "rack",
                            SortOrder = 239,
                            Value = "F15"
                        },
                        new
                        {
                            Id = 273,
                            Category = "rack",
                            SortOrder = 240,
                            Value = "F16"
                        },
                        new
                        {
                            Id = 274,
                            Category = "rack",
                            SortOrder = 241,
                            Value = "F17"
                        },
                        new
                        {
                            Id = 275,
                            Category = "rack",
                            SortOrder = 242,
                            Value = "F18"
                        },
                        new
                        {
                            Id = 276,
                            Category = "rack",
                            SortOrder = 243,
                            Value = "F19"
                        },
                        new
                        {
                            Id = 277,
                            Category = "rack",
                            SortOrder = 244,
                            Value = "F20"
                        },
                        new
                        {
                            Id = 278,
                            Category = "rack",
                            SortOrder = 245,
                            Value = "F21"
                        },
                        new
                        {
                            Id = 279,
                            Category = "rack",
                            SortOrder = 246,
                            Value = "F22"
                        },
                        new
                        {
                            Id = 280,
                            Category = "rack",
                            SortOrder = 247,
                            Value = "F23"
                        },
                        new
                        {
                            Id = 281,
                            Category = "rack",
                            SortOrder = 248,
                            Value = "F24"
                        });
                });

            modelBuilder.Entity("MoMS.Server.Models.Entities.Preparation", b =>
                {
                    b.Property<string>("BackPlate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("back_plate");

                    b.Property<string>("BaseMould")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("base_mould");

                    b.Property<string>("BlowCore")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("blow_core");

                    b.Property<string>("BlowMould")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("blow_mould");

                    b.Property<string>("Ejector")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ejector");

                    b.Property<string>("HotRunner")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hot_runner");

                    b.Property<string>("InjectionCavity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("injection_cavity");

                    b.Property<string>("InjectionCore")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("injection_core");

                    b.Property<string>("LipCavity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lip_cavity");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.ToTable("preparation");
                });

            modelBuilder.Entity("MoMS.Server.Models.FullList", b =>
                {
                    b.Property<string>("SNum")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("S_NUM");

                    b.Property<long?>("AccumUsage")
                        .HasColumnType("bigint")
                        .HasColumnName("ACCUM_USAGE");

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ITEM");

                    b.Property<DateTime?>("LastServ")
                        .HasColumnType("datetime2")
                        .HasColumnName("LAST_SERV");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LEVEL");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOCATION");

                    b.Property<int?>("No")
                        .HasColumnType("int")
                        .HasColumnName("NO");

                    b.Property<DateTime?>("PlanServ")
                        .HasColumnType("datetime2")
                        .HasColumnName("PLAN_SERV");

                    b.Property<long?>("PlanUsage")
                        .HasColumnType("bigint")
                        .HasColumnName("PLAN_USAGE");

                    b.Property<string>("Rack")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RACK");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("REMARK");

                    b.Property<int?>("Repeat")
                        .HasColumnType("int")
                        .HasColumnName("REPEAT");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TYPE");

                    b.Property<long?>("Usage")
                        .HasColumnType("bigint")
                        .HasColumnName("USAGE");

                    b.HasKey("SNum");

                    b.ToTable("full_list");
                });

            modelBuilder.Entity("MoMS.Server.Models.Location", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("LOCATION");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORY");

                    b.HasKey("Name");

                    b.ToTable("location");
                });
#pragma warning restore 612, 618
        }
    }
}
